### ISSUE TITLE
使用重启命令无效

### ISSUE THREAD

**Issue by Reversedeer** [18870/nonebot-plugin-reboot#4]
默认20s的等待时间指令也无法响应，所以我改成了1s也不行，fastapi设置为flase
插件已正常加载，无任何报错，nonebot版本b5
![image](https://user-images.githubusercontent.com/87823528/212220630-0da1b5f3-28d9-4414-b14d-428cc7702dbf.png)
![image](https://user-images.githubusercontent.com/87823528/212220788-9c8028ef-28b9-44a1-b625-0a3daf68eb25.png)
![image](https://user-images.githubusercontent.com/87823528/212221351-6b93018f-9121-4afb-92d7-4b83287327b6.png)

**Comment by 18870** [comment]
需要向机器人**私聊发送**命令

**Comment by Reversedeer** [comment]
我用了这么长时间一直在群内发:D
瞎眼了

**Comment by devil233-ui** [comment]
> 需要向机器人**私聊发送**命令

阿哲，那为什么控制台显示响应了？能否适配下群聊？

![Image](https://github.com/user-attachments/assets/9e7d1d89-dc15-444d-b9c0-ce09432525b9)
